version: "2.2"

services:
  
  packetbeat:

    image: docker.elastic.co/beats/packetbeat:${STACK_VERSION}
    container_name: packetbeat
    volumes:
      - ./beat/packetbeat.docker.yml:/usr/share/packetbeat/packetbeat.yml
      - ./certs:/usr/share/elasticsearch/config/certs
    environment:
      - ELASTICSEARCH_HOSTS=["https://es04:9200"]
      - BEAT_PASSWORD=${BEAT_PASSWORD}


    cap_add:
      - NET_RAW
      - NET_ADMIN
   # network_mode: "host"  

  auditbeat:
   image: docker.elastic.co/beats/auditbeat:${STACK_VERSION}
   container_name: auditbeat

   cap_add:
     - AUDIT_CONTROL
     - AUDIT_READ
   user: root
   pid: host
   privileged: true 
   volumes:
      - ./beat/auditbeat.docker.yml:/usr/share/auditbeat/auditbeat.yml:ro
      - /var/log:/var/log:ro
      - ./certs:/usr/share/elasticsearch/config/certs
   environment:
      - ELASTICSEARCH_HOSTS=["https://es04:9200"]
      - BEAT_PASSWORD=${BEAT_PASSWORD}


