#filebeat.registry_file: /usr/share/filebeat/data/registry
#filebeat.config.prospectors:
#  path: ./prospectors.d/*.yml
#  reload.enabled: false


#filebeat.autodiscover:
#  providers:
#    - type: docker
#      hints.enabled: true

filebeat.modules:
- module: system
  syslog:
    enabled: true
- module: nginx
  access:
    enabled: true
    var.paths: ["/var/log/nginx/access.log*"]
  error:
    enabled: true
    var.paths: ["/var/log/nginx/error.log*"]

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: 'https://es03:9200'
  username: "elastic"
  password: "1234567g"

setup.kibana:

    host: "kibana:5601"
