packetbeat.interfaces.device: any
packetbeat.interfaces.auto_promisc_mode: true
packetbeat.flows:
  timeout: 30s
  period: 10s


packetbeat.protocols:

- type: icmp
  enabled: true
- type: ssh
  ports: [22,23]
packetbeat.protocols.dns:

  ports: [53]
  include_authorities: true
  include_additionals: true

packetbeat.protocols.http:
  ports: [80, 5601, 9200, 8080, 8081, 5000, 8002]



processors:
- add_cloud_metadata: ~


output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: 'packetbeat_writer'
  password: '${BEAT_PASSWORD:}'
  ssl:
    certificate_authorities: "/usr/share/elasticsearch/config/certs/ca/ca.crt"
    certificate: "/usr/share/elasticsearch/config/certs/packetbeat/packetbeat.crt"
    key: "/usr/share/elasticsearch/config/certs/packetbeat/packetbeat.key"
setup.kibana:

    host: "kibana:5601"
    username: 'kibana_system'
   
